apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 892303346730.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-repo
  newName: 892303346730.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-repo
  newTag: 0cd37b3d
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
